pull_request_rules:
  - name: automatic merge
    conditions:
      - base=master
      - "#assignee>=2"
      - "#approved-reviews-by>=1"
      # - "status-success=ci/circleci"
    actions:
      merge:
        method: merge
        # method: rebase
        # rebase_fallback: merge
        # strict: smart
      dismiss_reviews: {}
      delete_head_branch: {}
