service: scrap

custom:
  stage:  ${opt:stage, 'dev'}
  wsgi:
    app: app.app
    pythonBin: python3
    packRequirements: false
  kendra:
    account: 294038372338
  dynamodb:
    indexDB: kendra-buttons-index-${self:custom.stage}
  pythonRequirements:
    dockerizePip: true
    layer: true


provider:
  name: aws
  profile: everypython
  runtime: python3.8
  stage: dev
  region: us-west-2
  environment:
    indexDB: ${self:custom.dynamodb.indexDB}
    PYPPETEER_HOME: '/tmp/'
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
        - "sns:*"
        - "dynamodb:*"
      Resource:
        - "*"

package:
  exclude:
    - .venv/**
    - node_modules/**
  include:
    - bin/**
    - app.py
    - parser/**
    - utils.py

functions:
  graphql:
    memorySize: 512
    handler: wsgi_handler.handler
    timeout: 600
    events:
      - http: ANY /
        cors: true

      - http: 'ANY {proxy+}'
        cors: true

    layers:
      - { Ref: PythonRequirementsLambdaLayer }

plugins:
  - serverless-python-requirements
  - serverless-wsgi
resources:
  Resources:
    myDynamoDBTable: 
      Type: AWS::DynamoDB::Table
      Properties:
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: "user"
            AttributeType: "S"
          - AttributeName: "site"
            AttributeType: "S"
        KeySchema: 
          - 
            AttributeName: "user"
            KeyType: "HASH"
          - 
            AttributeName: "site"
            KeyType: "RANGE"
        TableName: "${self:custom.dynamodb.indexDB}"